### ISSUE TITLE
cronbin推送失败

### ISSUE THREAD

**Issue by C018** [theowenyoung/blog#83]
部署好之后用bark来通知，Notification when failed?下面框里写的是，`curl --location 'https://api.day.app/xxxxx/cron运行失败/在线cron任务执行失败，请及时查看。'`在服务器执行可以正常收到通知，填进去有服务访问失败收不到通知

**Comment by theowenyoung** [comment]
是否 day.app 限制了 Cloudflare 的IP？

![CleanShot 2024-09-27 at 14 15 04@2x](https://github.com/user-attachments/assets/938caf27-ae50-43ca-bb74-ec099b8b695d)

**Comment by C018** [comment]
自建的bark服务器，应该不会，试了day.app的也不行

**Comment by theowenyoung** [comment]
请问是否正确编码？

https://day.app/2021/06/barkfaq/

可以你的服务端 curl 做过兼容处理，但是js解析命令时无法兼容未编码的网址？


```
https://api.day.app/xxxxx/cron运行失败/在线cron任务执行失败，请及时查看
```

需要这样写：

```
https://api.day.app/xxxxx/cron%E8%BF%90%E8%A1%8C%E5%A4%B1%E8%B4%A5/%E5%9C%A8%E7%BA%BFcron%E4%BB%BB%E5%8A%A1%E6%89%A7%E8%A1%8C%E5%A4%B1%E8%B4%A5%EF%BC%8C%E8%AF%B7%E5%8F%8A%E6%97%B6%E6%9F%A5%E7%9C%8B
```


![CleanShot 2024-09-27 at 16 24 13@2x](https://github.com/user-attachments/assets/6364937e-cb0a-4f6f-9a21-f74a630f58d6)

**Comment by C018** [comment]
了解

**Comment by C018** [comment]
编码之后依然不行，太奇怪了

**Comment by C018** [comment]
换了apprise，填的下面这个也不行。
`curl -X POST -F "body=cron error" -F "tags=all" https://xxx.com/notify/apprise`

**Comment by theowenyoung** [comment]
我是否可以在哪个平台注册并测试这个推送系统？ 看起来他需要一个 api key?

**Comment by C018** [comment]
方便留个telegram吗

**Comment by theowenyoung** [comment]
https://t.me/itsowenhyoung

**Comment by C018** [comment]
是不是打错了，没找到用户

**Comment by theowenyoung** [comment]
https://t.me/itsowenyoung

**Comment by theowenyoung** [comment]
感谢报告，已修复。
